# Generated by Django 4.1.3 on 2022-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commands',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='emailsendlog',
            options={'ordering': ['-created_time'], 'verbose_name': 'mail sending log', 'verbose_name_plural': 'mail sending log'},
        ),
        migrations.AlterField(
            model_name='commands',
            name='command',
            field=models.CharField(max_length=2000, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='describe',
            field=models.CharField(max_length=300, verbose_name='command description'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Change the time'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='title',
            field=models.CharField(max_length=300, verbose_name='command title'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='content',
            field=models.TextField(verbose_name='email content'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='emailto',
            field=models.CharField(max_length=300, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='send_result',
            field=models.BooleanField(default=False, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='email title'),
        ),
    ]
