# Generated by Django 4.1.3 on 2022-12-20 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthconfig',
            options={'ordering': ['-created_time'], 'verbose_name': 'oauth configuration', 'verbose_name_plural': 'oauth configuration'},
        ),
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'ordering': ['-created_time'], 'verbose_name': 'oauthuser', 'verbose_name_plural': 'oauthuser'},
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='callback_url',
            field=models.CharField(default='http://www.baidu.com', max_length=200, verbose_name='callback address'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='whether to display'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Change the time'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='type',
            field=models.CharField(choices=[('weibo', 'Weibo'), ('google', 'Google'), ('github', 'GitHub'), ('facebook', 'FaceBook'), ('qq', 'QQ')], default='a', max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Change the time'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='nikename',
            field=models.CharField(max_length=50, verbose_name='Nick name'),
        ),
    ]
